###

GET http://localhost:4000/

###

GET http://localhost:4000/iPerf3


###

GET http://localhost:4000/Ping

###

GET http://localhost:4000/MyTraceRoute

###
GET http://localhost:4000/GPS

###
GET http://localhost:4000/api/files


//testing POST PUT DELETE
###
POST http://localhost:4000/api/info
Content-Type: application/json

{
    "information": "My name is Madhav"
}

###
PUT http://localhost:4000/api/info
Content-Type: application/json

{
    "information": "My name is Madhav"
}

###
//sending query parameters
PUT http://localhost:4000/api/?word=Madhav&banana=yellow