###

GET http://localhost:4000/

###

GET http://localhost:4000/iPerf3


###

GET http://localhost:4000/Ping

###

GET http://localhost:4000/MyTraceRoute

###
GET http://localhost:4000/GPS

###
GET http://localhost:4000/api/files

###
GET http://localhost:4000/teststatus

###
GET http://localhost:4000/TCP
